const INITIAL_MONTH = 1;
const INITIAL_DAY = 1;
const INITIAL_HOUR = 1;
const INITIAL_MINUTE = 0;
const INITIAL_SECOND = 0;
const INITIAL_MILLISECOND = 0;
const MAX_YEAR = 9999;
const MIN_YEAR = 1;
const MAX_MONTH = 13;
const MIN_MONTH = 1;
const MAX_DAY = 30;
const MIN_DAY = 1;
const MAX_HOUR = 12;
const MIN_HOUR = 1;
const MAX_MINUTE = 59;
const MIN_MINUTE = 0;
const MAX_SECOND = 59;
const MIN_SECOND = 0;
const MAX_MILLISECOND = 999;
const MIN_MILLISECOND = 0;

const HOUR_DIFFERENCE = 6;

module.exports = {
  INITIAL_MONTH,
  INITIAL_DAY,
  INITIAL_HOUR,
  INITIAL_MINUTE,
  INITIAL_SECOND,
  INITIAL_MILLISECOND,
  MAX_YEAR,
  MIN_YEAR,
  MAX_MONTH,
  MIN_MONTH,
  MAX_DAY,
  MIN_DAY,
  MAX_HOUR,
  MIN_HOUR,
  MAX_MINUTE,
  MIN_MINUTE,
  MAX_SECOND,
  MIN_SECOND,
  MAX_MILLISECOND,
  MIN_MILLISECOND,
  HOUR_DIFFERENCE,
};
